[supervisord]
nodaemon=true
pidfile=/tmp/supervisord.pid
logfile=/tmp/supervisord.log
childlogdir=/tmp

[program:xvfb]
command=/usr/bin/Xvfb :0 -screen 0 1600x900x24 -nolisten tcp -ac
priority=10
autostart=true
autorestart=true
stdout_logfile=/tmp/xvfb.log
stderr_logfile=/tmp/xvfb.err

[program:openbox]
command=/usr/local/bin/wait-for-x /usr/bin/dbus-run-session -- /usr/bin/openbox-session
priority=20
autostart=true
autorestart=true
stdout_logfile=/tmp/openbox.log
stderr_logfile=/tmp/openbox.err
environment=DISPLAY=":0",HOME="/home/analyst"

[program:x11vnc]
command=/usr/local/bin/wait-for-x /usr/bin/x11vnc -display :0 -nopw -forever -shared -localhost -rfbport 5900 -noxdamage
priority=30
autostart=true
autorestart=true
stdout_logfile=/tmp/x11vnc.log
stderr_logfile=/tmp/x11vnc.err
environment=DISPLAY=":0",HOME="/home/analyst"

[program:websockify]
command=/usr/bin/websockify --web=/usr/share/novnc 6080 localhost:5900
priority=40
autostart=true
autorestart=true
stdout_logfile=/tmp/websockify.log
stderr_logfile=/tmp/websockify.err

[program:wireshark]
command=/usr/local/bin/wait-for-x /usr/bin/wireshark -i eth0 -k -f "udp port 53 or tcp port 53"
priority=50
autostart=true
autorestart=true
startsecs=3
stdout_logfile=/tmp/wireshark.log
stderr_logfile=/tmp/wireshark.err
environment=DISPLAY=":0",HOME="/home/analyst"
